version: '3.9'
services:
  api:
    image: elevator_storage
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"]
    restart: always
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    env_file: ./.env
    volumes:
      - api-data:/app/data

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: elevator_storage_prod
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - my-db:/var/lib/mysql

  wait-for-db:
    image: eficode/wait-for
    depends_on:
      - db
    command: ["db:3306", "--timeout=300", "--", "echo", "success"]

volumes:
  my-db:
  api-data: